---
title: "Welcome to my portal!"
output: 
  html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\
\
\

## About Me

Hi, this is Bingling. When I was an undergraduate at William & Mary, I majored in Psychology and Economics. I was fascinated with the intersection of both fields, behavioral economics, and its application to consumer behavior and marketing. Following my passion, I am currently a student at the Master of Behavioral and Decision Science program at the University of Pennsylvania. I love applying my knowledge of behavioral and decision science to solve real-world problems. I want to help people make more beneficial choices. I am passionate about designing and promoting human-centered ideas and products to make the world better. I love working in a fast-paced environment. I enjoy transferring insights from multiple fields into workable actions. I am enthusiastic about taking on challenges and exploring the unknown.

\

Here, you may see samples of my work on data science, research, as well as consumer insights and product development at the Design Challenges.

\

## Contact

Email: <a href="mailto:bingling@sas.upenn.edu">bingling@sas.upenn.edu</a>
\
Linkedin: <a href="www.linkedin.com/in/bingling-wang"> www.linkedin.com/in/bingling-wang</a>